### ISSUE TITLE
[request]: fix awscli/awsebcli botocore conflict

### ISSUE THREAD

**Issue by shaicoleman** [aws/aws-elastic-beanstalk-cli#2]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
When installing the latest versions of awscli and awsebcli, I'm getting a version conflict of `botocore`
```
pip3 install --upgrade --user awscli
pip3 install --upgrade --user awsebcli
ERROR: awscli 1.17.2 has requirement botocore==1.14.2, but you'll have botocore 1.13.50 which is incompatible.
```

**Are you currently working around this issue?**
Workaround is to install an old version of awscli
`pip3 install --upgrade --user 'awscli<1.17' awsebcli`

Or use something like virtualenv/pipenv

**Comment by JordanRosas** [comment]
Thanks for the workaround. 
I had gotten all this set up back in December and right after January 1 it got all messed up and this finally got me up an running again!

**Comment by halcarleton** [comment]
Closing this issue as [awsebcli 3.17.1](https://pypi.org/project/awsebcli/3.17.1/) has been released with a fix for this conflict.

Thank you for reporting this!

**Comment by shaicoleman** [comment]
If this happens again in the future, a very easy workaround is using the `pipx` tool, just run `pipx install awsebcli`

**Comment by spawn-guy** [comment]
@halcarleton this issue is re-introduced with latest `awseb` and `awsebcli` versions. will you be so kind to introduce a general fix for future releases instead of hotfixing this? Maybe, talk to "the other" team and produce a consensus?

```
awsebcli 3.19.0 requires botocore<1.18,>=1.17, but you'll have botocore 1.18.7 which is incompatible.
awscli 1.18.14 requires botocore==1.15.14, but you'll have botocore 1.17.63 which is incompatible.
```

**Comment by geraldstanje** [comment]
same:
```
ERROR: awsebcli 3.19.3 has requirement botocore<1.20.0,>=1.19.0, but you'll have botocore 1.20.5 which is incompatible.
```

**Comment by dennisvang** [comment]
And again:
```
...
[pipenv.exceptions.DependencyConflict]: The operation failed... A dependency conflict was detected and could not be resolved.
ERROR: Cannot resolve botocore (1.20.15) due to conflicting parent dependencies: 
        awsebcli => botocore (>=1.19.0,<1.20.0)

```

**Comment by shaicoleman** [comment]
Just use the pipx tool
https://pipxproject.github.io/pipx/

**Comment by dennisvang** [comment]
Thanks for the suggestion, but I was actually hoping for a proper solution from AWS. No offense, but I'm not really looking for yet another `pip<something>` just to install AWS stuff that *should* simply work, out-of-the box, with plain old `pip`.

**Comment by dennisvang** [comment]
... and yet again: my working `Pipfile.lock` has `awsebcli` version 3.19.3, with `urllib3` version 1.26.3, but I cannot update:

`ERROR: Cannot resolve urllib3 (1.26.5) due to conflicting parent dependencies: 
        awsebcli => urllib3 (>=1.25.4,<1.26)`

How can this be? `awsebcli` 3.19.3 was installed with `urllib3` 1.26.3 before, but now, all of a sudden, `urllib3`  must be <1.26?

This is forcing me to freeze `awsebcli`, `boto3`, `botocore`, and `urllib3` in the `Pipfile`.

The "highly recommended" EB CLI installation scripts provide an inconvenient workaround. That is *not* a solution. So why is this issue closed?

As (one of) the largest cloud computing service provider(s) in the world, I would expect AWS to be able to fix this properly.

**Comment by prenaux** [comment]
Same issue again when updating...

**Comment by chadamski** [comment]
Just adding to this thread to suggest this issue should not be closed. Ran into this dependency conflict again today when deploying my Django application.

**Comment by senluowanxiangxiaoyaozizai** [comment]
this issue is still unresolved after 3 years....

**Comment by geraldstanje** [comment]
hi guys - can someone look into that?

**Comment by jsheld** [comment]
This should be resolved. Dependabot is updating our botocore library version in lock step with the same change being made with the awscli. However, if you install the two cli's days apart, you may run into this issue since the package is updated daily.

**Comment by geraldstanje** [comment]
@jsheld if i look at aws-elastic-beanstalk-cli and aws-cli i see that they use different versions of botocore still:
```
latest [aws-elastic-beanstalk-cli](https://github.com/aws/aws-elastic-beanstalk-cli/tree/master) requires botocore>1.23.41,<1.29.124

https://github.com/aws/aws-cli/blob/develop/setup.cfg is on botocore==1.29.133

https://pypi.org/project/botocore/#history ... is on 1.29.133
```

**Comment by jsheld** [comment]
Thanks for clarifying. I was scoping this to the awscli and ebcli versions on GitHub.

**Comment by geraldstanje** [comment]
@jsheld if i only look at pypi:
```
https://pypi.org/project/awsebcli/ ... awsebcli 3.20.6, requires: botocore>1.23.41,<1.29.119
https://pypi.org/project/awscli/#history ... awscli 1.27.134, requires: botocore==1.29.134
https://pypi.org/project/botocore/#history ... botocore 1.29.134
```

**Comment by JUSTSUJAY** [comment]
As of today, the issue still persists as

awscli 1.32.7 requires botocore==1.34.7
awsebcli 3.20.10 requires botocore<1.32.0,>1.23.41

What is the correct botocore version that is compatible with both?

**Comment by syedmharis** [comment]
Still getting ERROR: 

pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.

awsebcli 3.20.10 requires botocore<1.32.0,>1.23.41, but you have botocore 1.35.8 which is incompatible.
