### ISSUE TITLE
EB deploy with EBCLI 3.20.5 causes missing custom configuration

### ISSUE THREAD

**Issue by ttomaszewski** [aws/aws-elastic-beanstalk-cli#342]
### Description
Running `eb deploy` using EBCLI 3.20.5 causes missing custom configuration on the servers

### Steps to reproduce
Use `eb deploy` for an app with custom configuration in `.platform` or `.elasticbeanstalk`

### Observed result
Custom configuration files are missing from the expected directories on the server instances during SSH.

### Expected result
Custom configuration exists on the server instances during SSH.

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: Linux
2. EBCLI version: 3.20.5

### Workaround
Downgrading EBCLI to 3.20.3 works as expected and includes the custom configuration

**Comment by yohanthshetty** [comment]
Hi @ttomaszewski , Thanks for bringing this to our notice. Any inconvenience is regretted.
Can you please share the output when you use `eb deploy --verbose` with 3.20.5.

**Comment by BiggerNoise** [comment]
We're seeing this as well:

```
$ eb --version
EB CLI 3.20.5 (Python 3.8.10 (default, Nov 14 2022, 12:59:47)
[GCC 9.4.0])
```

It may be related to how we're using the ebigore file. JiC, here's our .ebignore:
```
# Ignore everything
*
# Then include what we want
!Dockerrun.aws.json
!.ebextensions/
!.platform/

#Need to explicitly exclude templates because it's getting pulled in b/c of the above directory inclusions
templates/
```

**Comment by BiggerNoise** [comment]
Here's part of the log from our deploy. We expand the files such as scripts.config that are in our templates directory to the .ebextensions directory.

.ebextensions and .platform are being skipped.

Hope this is helpful; let me know if there's further information I can provide

[verbose_deploy.txt](https://github.com/aws/aws-elastic-beanstalk-cli/files/10934406/verbose_deploy.txt)

**Comment by BiggerNoise** [comment]
I can confirm that after rolling back eb cli to 3.20.3, this is working again.

**Comment by yohanthshetty** [comment]
Hi @BiggerNoise, Thanks for the details. Looks like the .ebignore file is skipping every file. Team will look into this soon and post any correspondence here. 
Appreciate your time.

**Comment by ttomaszewski** [comment]
Thanks for sharing that output @BiggerNoise !

**Comment by yohanthshetty** [comment]
issue should be fixed in the upcoming release.

**Comment by yohanthshetty** [comment]
Hi @BiggerNoise @ttomaszewski , New version for EBCLI has been released. Please update the ebcli version by referring [docs](https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/eb-cli3-install-advanced.html).

**Comment by karol-burczynski-ck** [comment]
Hi, I can confirm that 3.20.6 have fixed that issue :muscle:

**Comment by Ghost93** [comment]
Hi,

Looks like I have the same problem running EB cli on MacOS, version 3.20.10.
I'm deploying one big jar that includes `.platform` and `.ebextensions`. 
Looks like the `.ebextensions` do work, but the `.platform` part does not. The nginx configuration isn't updating.

Any ideas? Tried to downgrade to 3.20.8 but still the same problem.

Versions, and deploy script output:

```
$ eb --version 
EB CLI 3.20.8 (Python 3.11.6 (main, Nov  2 2023, 04:52:24) [Clang 14.0.3 (clang-1403.0.22.14.1)])
```

```
$ eb --version                                                                                                                                                
EB CLI 3.20.10 (Python 3.11.6 (main, Nov  2 2023, 04:52:24) [Clang 14.0.3 (clang-1403.0.22.14.1)])
```

```
$ ./deploy.sh
<... irrelevant maven output here from jar compiling and packaging ..>

[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  41.822 s
[INFO] Finished at: 2023-11-22T12:46:42+02:00
[INFO] ------------------------------------------------------------------------

<.. using `jar uvf` to add files to jar, redacted some file names..>
adding: target/git.properties(in = 434) (out= 238)(deflated 45%)
Added git.properties to jar
adding: .ebextensions/(in = 0) (out= 0)(stored 0%)
adding: .ebextensions/**********.config(in = 1670) (out= 666)(deflated 60%)
adding: .platform/(in = 0) (out= 0)(stored 0%)
adding: .platform/nginx/(in = 0) (out= 0)(stored 0%)
adding: .platform/nginx/conf.d/(in = 0) (out= 0)(stored 0%)
adding: .platform/nginx/conf.d/***********.conf(in = 665) (out= 286)(deflated 56%)
adding: .platform/nginx/conf.d/***********.conf(in = 477) (out= 224)(deflated 53%)
adding: .platform/nginx/conf.d/***********.conf(in = 509) (out= 237)(deflated 53%)
adding: .platform/nginx/conf.d/***********.conf(in = 132) (out= 105)(deflated 20%)
adding: .platform/nginx/conf.d/***********.conf(in = 482) (out= 227)(deflated 52%)
adding: .platform/nginx/conf.d/***********.conf(in = 489) (out= 228)(deflated 53%)
adding: .platform/nginx/conf.d/***********.conf(in = 266) (out= 174)(deflated 34%)
adding: .platform/nginx/conf.d/***********.conf(in = 419) (out= 154)(deflated 63%)
adding: .platform/nginx/conf.d/***********.conf(in = 85) (out= 80)(deflated 5%)
adding: .platform/nginx/conf.d/***********(in = 60) (out= 62)(deflated -3%)
adding: .platform/nginx/nginx.conf(in = 1145) (out= 520)(deflated 54%)

< .... call to eb deploy: .....>
< .... eb deploy MY_ENV_NAME --verbose -l MY_VERSION_TAG --timeout 15 .....>
INFO: Deploying code to MY_ENV_NAME in region eu-west-1
INFO: Uploading archive to s3 location: MY_APP_NAME/MY_VERSION_TAG.jar
Uploading: [##################################################] 100% Done...
INFO: Creating AppVersion MY_VERSION_TAG
2023-11-22 10:47:04    INFO    Environment update is starting.      
2023-11-22 10:47:11    INFO    Deploying new version to instance(s).
2023-11-22 10:47:17    INFO    Instance deployment successfully detected a JAR file in your source bundle.
2023-11-22 10:47:17    INFO    Instance deployment successfully generated a 'Procfile'.
2023-11-22 10:47:24    INFO    Instance deployment completed successfully.
2023-11-22 10:47:29    INFO    New application version was deployed to running EC2 instances.
2023-11-22 10:47:29    INFO    Environment update completed successfully.
```
